name: imperium_bot
description: Autonomous bot for solo version of imperium
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  font_awesome_flutter: ^10.1.0
  top_snackbar_flutter: ^1.0.2
  google_fonts: ^2.3.2
  tuple: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/csv/
    - assets/csv/commons/
    - assets/csv/factions/
    - assets/images/
